task_name:
  "mme-realworld"

work_dir:
  "/data9/zilun/ImageRAG0214/codebase"

input_image_dir:
  "/data9/shz/dataset/MME-RealWorld/"

patch_saving_dir:
  "cache/patch/mmerealworld"

model_input_image_size:
  448

use_dynamic:
  1

fast_path_T:
  30

num_chunks:
  1

chunk_idx:
  0

mode:
  "baseline"

paraphrase_model:
    model_name:
      "Qwen2.5-32B-Instruct"
    model_path:
        "Qwen2.5-32B-Instruct"
    generation_config:
        temperature:
            1.0
        top_p:
            0.99
        max_tokens:
            512
        timeout:
            60

kw_model:
#    model_path:
#        "/media/zilun/wd-161/hf_download/all-MiniLM-L6-v2"
#    generation_config:
#        temperature:
#            0.99
#        top_p:
#            0.95
#        max_tokens:
#            512
#        timeout:
#            60

text_expansion_model:

text_embed_model:
    model_path:
      "/data9/zilun/ImageRAG0214/checkpoint/all-MiniLM-L6-v2"


fast_vlm_model:
    model_name:
      "georsclip"
    model_path:
      "/data9/zilun/ImageRAG0214/checkpoint/RS5M_ViT-L-14-336.pt"
    original_clip_path:
      "/data9/zilun/ImageRAG0214/checkpoint/clip-vit-large-patch14-336"


llmvqa_model:
  model_name:
    "internvl"
  model_path:
      "/data9/zilun/ImageRAG0214/checkpoint/InternVL2_5-8B"

  load_in_8bit:
    True

  generation_config:
      temperature:
          0.2
      top_p:

      max_tokens:
          512
      timeout:
          60
      num_beams:
          1

vector_database:
    # legacy rs dataset
    lrsd_meta_pkl_path:
        "/data9/zilun/ImageRAG0214/data/georsclip_feat_label_all_server.pkl"
    pub11_meta_pkl_path:
        "/data9/zilun/ImageRAG0214/data/georsclip_pub11feat_label_3M.pkl"
    lrsd_vector_database_dir:
      "cache/vector_database/lrsd_vector_database"
    pub11_vector_database_dir:
      "cache/vector_database/pub11_vector_database"
    mm_vector_database_dir:
      "cache/vector_database/mm_vector_database"

question_file_path:
  "/data9/zilun/ImageRAG0214/codebase/inference/MME-RealWorld-RS/MME_RealWorld.json"

answers_file_path:
  "/data9/zilun/ImageRAG0214/data/eval/answer_MME-RealWorld-RS_InternVL8B_dynamic12_baseline.jsonl"

batch_size:
  4

test_prompt:
  "Select the best answer to the above multiple-choice question based on the image. Respond with only the letter (A, B, C, D, or E) of the correct option."
#  "Select the best answer to the above multiple-choice question based on the image. Provide the thinking process and give the response in the end with the letter (A, B, C, D, or E) of the correct option."
#  "Select the best answer to the above multiple-choice question based on the image. Letâ€™s think step by step, and give the final response with the letter (A, B, C, D, or E) of the correct option."